#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# OpenClaw Stack — First-Time Setup
# ============================================================
# Interactive wizard to configure your .env and start the stack.
# Usage: ./scripts/setup.sh
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo -e "${CYAN}============================================================${NC}"
echo -e "${CYAN}  OpenClaw Stack — Setup Wizard${NC}"
echo -e "${CYAN}============================================================${NC}"
echo ""

# Check Docker
if ! command -v docker &> /dev/null; then
  echo -e "${RED}Docker is not installed. Please install Docker first.${NC}"
  echo "  → https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker compose version &> /dev/null; then
  echo -e "${RED}Docker Compose v2 is required.${NC}"
  exit 1
fi

echo -e "${GREEN}✓${NC} Docker and Docker Compose detected"
echo ""

# Check if .env already exists
if [[ -f "${PROJECT_DIR}/.env" ]]; then
  echo -e "${YELLOW}A .env file already exists.${NC}"
  read -rp "Overwrite it? (y/N): " OVERWRITE
  if [[ "$OVERWRITE" != "y" && "$OVERWRITE" != "Y" ]]; then
    echo "Keeping existing .env. Starting stack..."
    cd "$PROJECT_DIR"
    docker compose up -d
    echo ""
    echo -e "${GREEN}Stack started!${NC} Message your Telegram bot to get started."
    exit 0
  fi
fi

# Collect configuration
echo -e "${BLUE}Let's configure your stack. You'll need:${NC}"
echo "  1. A Tailscale auth key"
echo "  2. An Anthropic (or OpenAI) API key"
echo "  3. A Telegram bot token from @BotFather"
echo ""

# Tailscale
echo -e "${CYAN}--- Tailscale ---${NC}"
echo "Get an auth key from: https://login.tailscale.com/admin/settings/keys"
read -rsp "Tailscale auth key: " TS_AUTHKEY
echo ""
echo ""

# Gateway token
echo -e "${CYAN}--- Gateway Token ---${NC}"
OPENCLAW_TOKEN=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p | tr -d '\n' | head -c 64)
BROWSER_TOKEN=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p | tr -d '\n' | head -c 64)
echo -e "Generated gateway token: ${GREEN}${OPENCLAW_TOKEN:0:16}...${NC} (saved to .env)"
echo ""

# AI Provider
echo -e "${CYAN}--- AI Provider ---${NC}"
echo "Get an Anthropic key from: https://console.anthropic.com/settings/keys"
read -rsp "Anthropic API key: " ANTHROPIC_API_KEY
echo ""
echo ""

# Telegram
echo -e "${CYAN}--- Telegram Bot ---${NC}"
echo "Create a bot via @BotFather on Telegram"
read -rsp "Telegram bot token: " TELEGRAM_BOT_TOKEN
echo ""

# Validate Telegram token (POST to avoid token in URL / process list)
echo ""
echo -n "Validating Telegram token... "
TELEGRAM_RESPONSE=$(curl -s -X POST \
  -H "Content-Type: application/json" \
  -d "{\"chat_id\":\"\"}" \
  "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe" 2>/dev/null || echo '{"ok":false}')

if echo "$TELEGRAM_RESPONSE" | grep -q '"ok":true'; then
  BOT_USERNAME=$(echo "$TELEGRAM_RESPONSE" | grep -o '"username":"[^"]*"' | head -1 | cut -d'"' -f4)
  echo -e "${GREEN}✓${NC} Valid! Bot: @${BOT_USERNAME}"
else
  echo -e "${YELLOW}⚠ Could not validate token. Proceeding anyway.${NC}"
fi
echo ""

# Write .env
cat > "${PROJECT_DIR}/.env" << EOF
# OpenClaw Stack — Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

# Tailscale
TS_AUTHKEY=${TS_AUTHKEY}

# OpenClaw Gateway
OPENCLAW_TOKEN=${OPENCLAW_TOKEN}

# Browser security token
BROWSER_TOKEN=${BROWSER_TOKEN}

# AI Provider
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# Telegram
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
EOF

chmod 600 "${PROJECT_DIR}/.env"
echo -e "${GREEN}✓${NC} .env created (permissions: 600)"

# Create data directories
mkdir -p "${PROJECT_DIR}/data/.openclaw"
mkdir -p "${PROJECT_DIR}/data/workspace"

# Fix permissions for container (runs as uid 1000)
if [[ "$(id -u)" == "0" ]]; then
  chown -R 1000:1000 "${PROJECT_DIR}/data"
  echo -e "${GREEN}✓${NC} Data directory permissions set"
fi

# Start the stack
echo ""
echo -e "${BLUE}Starting the stack...${NC}"
cd "$PROJECT_DIR"
docker compose up -d

echo ""
echo -e "${CYAN}============================================================${NC}"
echo -e "${GREEN}  Setup Complete!${NC}"
echo -e "${CYAN}============================================================${NC}"
echo ""
echo "  Your bot is starting up. Give it ~30 seconds, then:"
echo ""
echo "  1. Open Telegram"
echo "  2. Search for @${BOT_USERNAME:-your-bot}"
echo "  3. Press Start and say hello!"
echo ""
echo "  Useful commands:"
echo "    docker compose ps              # Check status"
echo "    docker compose logs -f         # View logs"
echo "    docker compose down            # Stop everything"
echo ""
echo "  Gateway token (for Control UI):"
echo "    ${OPENCLAW_TOKEN:0:16}... (see .env for full token)"
echo ""
echo -e "${CYAN}============================================================${NC}"
